//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }

        public override string ToString()
        {
            return $"Last name: {LastName} first name: {FirstName} birth date {BirthDate.ToLongDateString()}";
        }
    }
}
